management:
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  instance:
    healthCheckUrlPath: /actuator/health
    statusPageUrlPath: /actuator/info
    hostname: localhost
    leaseRenewalIntervalInSeconds: '10'
  client:
    register-with-client: 'true'
    fetch-registry: 'true'
    service-url:
      defaultZone: http://localhost:8761/
